### ISSUE TITLE
Can I change to 3D?

### ISSUE THREAD

**Issue by OanaGugea** [wwwtyro/Astray#8]
Hello! I really like this game and I start looking at the code and I was wondering if there is any posibility to change it to 3D, I mean moving the camera from above into the maze? I try to learn webGl, so I am sorry if my question is out of the content, but I am new in ths field....

**Comment by wwwtyro** [comment]
Hi Oana - yes, certainly. I would probably start here: https://github.com/wwwtyro/Astray/blob/master/index.html#L175-L177

**Comment by OanaGugea** [comment]
Thank you! Could you, please, give me more details, or explain me how should I think, so I can implement it?
